[tool.poetry]
name = "falocalrepo"
version = "3.23.8"
description = "Pure Python program to download any user's gallery, scraps, favorites, and journals from FurAffinity in an easily handled database."
authors = ["Matteo Campinoti <matteo.campinoti94@gmail.com>"]
license = "EUPL-1.2"
readme = "README.md"
homepage = "https://gitlab.com/MatteoCampinoti94/FALocalRepo"
repository = "https://gitlab.com/MatteoCampinoti94/FALocalRepo"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
]

[tool.poetry.scripts]
falocalrepo = "falocalrepo.__main__:main"

[tool.poetry.dependencies]
python = "^3.9"
faapi = "~2.18.0"
falocalrepo-database = "~4.16.2"
falocalrepo-server = "~1.10.0"
psutil = "^5.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
